const CHANGE_INPUT_ACTION = 'CHANGE_INPUT',
    VIEW_PRODUCT_ACTION = 'VIEW_PRODUCT',
    ADD_TO_CART_ACTION = 'ADD_TO_CART',
    OPEN_CART_ACTION = 'OPEN_CART';
export {CHANGE_INPUT_ACTION,
VIEW_PRODUCT_ACTION,
ADD_TO_CART_ACTION,
OPEN_CART_ACTION}