const TOGGLE_PRODUCT_VIEW_ACTION = 'TOGGLE_PRODUCT_VIEW',
    TOGGLE_CART_VIEW_ACTION = 'TOGGLE_CART_VIEW',
    REMOVE_ITEM_FROM_CART_ACTION = 'REMOVE_ITEM_FROM_CART',
    ADD_TO_CART_ACTION = 'ADD_TO_CART';
export {TOGGLE_PRODUCT_VIEW_ACTION,
TOGGLE_CART_VIEW_ACTION,
REMOVE_ITEM_FROM_CART_ACTION,
ADD_TO_CART_ACTION}